[package]
name = "easy-addr"
version.workspace = true
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
cosmwasm-std = { version = "2.2.0", features = [
  "cosmwasm_1_4",
  # Enable this if you only deploy to chains that have CosmWasm 2.0 or higher
  # "cosmwasm_2_0",
  # Or this if you only deploy to chains that have CosmWasm 2.1 or higher
  # "cosmwasm_2_1",
] }
proc-macro2 = "1"
quote = "1"
syn = { version = "1.0.6", features = ["full", "printing", "extra-traits"] }